sequenceDiagram
    alt User cancels subscription
        User ->> Carrier: 1. User fires cancellation event.
    else Max rebill tries achieved
        Carrier ->> Carrier: 1. Cancels subscription for user after many retries.
    end
    Carrier ->> Movile: 2. Sends cancellation notification
    Movile ->> User: 3. Sends cancellation message
    Movile ->> Ubook: 4. Notifies cancellation event (id, carrier, phone)
