sequenceDiagram
    alt Through SMS message
        User ->> Carrier: 1. Sends SMS message for subscription.
    else Through web landing page
        User ->> Movile: 1.A. User requests for product subscription
        Movile ->> Carrier: 1.B. Requests for user subscription
    end

    Carrier ->> Carrier: 2. Charges amount to user.
    Carrier ->> Movile: 3. Notifies user subscription to product
    Note right of Carrier: In Personal AR, current configuration for subscription event means billed or enqueued for rebill.

    Movile ->> User: 4. Sends URL to site with phone number as parameter.
    Movile ->> Ubook: 5. Notifies subscription event (id, carrier, phone)

    Carrier ->> Movile: 6. Notifies billing result.
    Movile ->> Ubook: 7. Notifies billing event.

    User ->> Ubook: 8. Access URL for default auth credentials.
    User ->> Ubook: 9. Changes credentials.
